"""empty message

Revision ID: af6e6a0d2b78
Revises: 
Create Date: 2024-09-14 12:37:29.384414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6e6a0d2b78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zadatak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=200), nullable=False),
    sa.Column('opis', sa.String(length=500), nullable=True),
    sa.Column('uradjeno', sa.Boolean(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadatak')
    # ### end Alembic commands ###
